### ISSUE TITLE
Use values from the TRMs?

### ISSUE THREAD

**Issue by MabezDev** [bjoernQ/espsegs#1]
I think whilst more it's verbose, it would be good to list all the physical SRAM locations as is from the TRM, this includes sections which may or may not be used for cache etc. I think having this tool as a source of truth may help us when writing the linker scripts (and checking them)

**Comment by bjoernQ** [comment]
I was thinking about taking the addresses from esp-idf's `soc.h` since it's a bit more readable - but there is definitely something to improve here. Thanks for reminding me
